import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_six.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_icon_button.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'models/khichiq_leads_edit_twentyfour_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_leads_edit_twentyfour_provider.dart';class KhichiqLeadsEditTwentyfourScreen extends StatefulWidget {const KhichiqLeadsEditTwentyfourScreen({Key? key}) : super(key: key);

@override KhichiqLeadsEditTwentyfourScreenState createState() =>  KhichiqLeadsEditTwentyfourScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqLeadsEditTwentyfourProvider(), child: KhichiqLeadsEditTwentyfourScreen()); } 
 }
class KhichiqLeadsEditTwentyfourScreenState extends State<KhichiqLeadsEditTwentyfourScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_order_details".tr, style: theme.textTheme.titleSmall), SizedBox(height: 7.v), _buildFrameSeventyFour(context), SizedBox(height: 24.v), _buildNextTask(context), SizedBox(height: 6.v), _buildFrameSeventyFive(context), SizedBox(height: 24.v), Text("msg_events_wise_details".tr, style: theme.textTheme.titleSmall), SizedBox(height: 7.v), _buildFrame(context), SizedBox(height: 12.v), _buildDate(context), SizedBox(height: 12.v), _buildFrame1(context), SizedBox(height: 24.v), _buildOrderPayments(context), SizedBox(height: 8.v), _buildFrameSeventyTwo(context), SizedBox(height: 24.v), Text("lbl_notes".tr, style: theme.textTheme.titleSmall), SizedBox(height: 10.v), _buildFrame2(context), SizedBox(height: 24.v), Text("lbl_clients".tr, style: theme.textTheme.titleSmall), SizedBox(height: 10.v), _buildFrame3(context), SizedBox(height: 13.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgArchive, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_archive_this_order".tr, style: CustomTextStyles.labelLargePrimary))])])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 64.v, leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 24.v, bottom: 24.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgWeddingIcon, margin: EdgeInsets.only(top: 3.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Column(children: [AppbarSubtitleTwo(text: "msg_siddheshwar_shreyasi".tr), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 72.h), child: Row(children: [AppbarSubtitleSix(text: "lbl_wedding3".tr.toUpperCase()), Padding(padding: EdgeInsets.only(bottom: 1.v), child: SizedBox(child: Divider(indent: 9.h))), AppbarSubtitleSix(text: "lbl_upcoming".tr.toUpperCase(), margin: EdgeInsets.only(left: 7.h))]))]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEdit, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))], styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildFrameSeventyFour(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 11.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_pre_wedding4".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_engagement2".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_haldi".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_wedding4".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_siddheshwar_9820098200".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 5.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_siddheshwar_anant_yahoo_co_in".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 14.v), Padding(padding: EdgeInsets.symmetric(horizontal: 53.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGmail, height: 20.adaptSize, width: 20.adaptSize), Spacer(flex: 25), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v)), Spacer(flex: 24), CustomImageView(imagePath: ImageConstant.imgSocial, height: 20.adaptSize, width: 20.adaptSize), Spacer(flex: 25), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v)), Spacer(flex: 24), CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), child: CustomImageView(imagePath: ImageConstant.imgCall))]))])); } 
/// Section Widget
Widget _buildNextTask(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_next_task".tr, style: theme.textTheme.titleSmall)), Text("msg_due_by_28_feb_23".tr, style: CustomTextStyles.bodyMediumOrange600)]); } 
/// Section Widget
Widget _buildFrameSeventyFive(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.whiteA700, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.indigo100.withOpacity(0.5), width: 1.h), borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 63.v, width: 343.h, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 6.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: Container(height: 48.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h)))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 12.h, bottom: 11.v), child: Text("msg_take_confirmation".tr, style: theme.textTheme.titleMedium)))]))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 16.v, width: 323.h, child: Stack(alignment: Alignment.bottomLeft, children: [_buildEVENTCounter(context, eVENTCounter: "lbl_event_12".tr), Align(alignment: Alignment.bottomLeft, child: Container(height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 55.h), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 4.v), decoration: AppDecoration.success.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgVectorGray50, height: 4.v, width: 6.h, alignment: Alignment.centerRight)))])), SizedBox(height: 9.v), Divider(), SizedBox(height: 11.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildEngagement1(context, engagement: "lbl_pre_wedding".tr, time: "msg_30_aug_2023_4_00pm".tr)), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildDate(BuildContext context) { return SizedBox(height: 172.v, width: 343.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildEVENTCounter(context, eVENTCounter: "lbl_event_22".tr)), SizedBox(height: 9.v), Divider(), SizedBox(height: 12.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildEngagement1(context, engagement: "lbl_engagement3".tr, time: "msg_30_aug_2023_4_00pm".tr)), SizedBox(height: 1.v)]))), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_event_3".tr, style: theme.textTheme.bodySmall), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 40.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 1.v), decoration: AppDecoration.fillOrange.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_team".tr.toUpperCase(), style: CustomTextStyles.bodySmallOrange600)), CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 10.h))])])), SizedBox(height: 9.v), Divider(), SizedBox(height: 7.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildEngagement1(context, engagement: "lbl_haldi2".tr, time: "msg_30_aug_2023_4_00pm".tr)), SizedBox(height: 7.v)]))), Padding(padding: EdgeInsets.only(top: 58.v), child: Selector<KhichiqLeadsEditTwentyfourProvider, TextEditingController?>(selector: (context, provider) => provider.dateController, builder: (context, dateController, child) {return CustomTextFormField(width: 343.h, controller: dateController, hintText: "msg_your_order_has_been2".tr, textInputAction: TextInputAction.done, alignment: Alignment.topCenter, contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 10.v), borderDecoration: TextFormFieldStyleHelper.fillOnPrimary, fillColor: theme.colorScheme.onPrimary.withOpacity(0.95));}))])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildOverview(context, overview: "lbl_event_4".tr, price: "lbl_team".tr)), SizedBox(height: 10.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildEngagement1(context, engagement: "lbl_wedding".tr, time: "msg_30_aug_2023_4_00pm".tr)), SizedBox(height: 4.v)])); } 
/// Section Widget
Widget _buildOrderPayments(BuildContext context) { return Row(children: [Text("lbl_order_payments".tr, style: theme.textTheme.titleSmall), Spacer(), CustomImageView(imagePath: ImageConstant.imgFloatingIcon, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_add".tr, style: CustomTextStyles.labelLargePrimary))]); } 
/// Section Widget
Widget _buildFrameSeventyTwo(BuildContext context) { return Container(decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 8.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildOverview(context, overview: "lbl_overview".tr, price: "lbl_payment".tr)), SizedBox(height: 10.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_quoted".tr, augTwentyThree: "lbl_2_50_000_00".tr)), SizedBox(height: 10.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_received".tr, augTwentyThree: "lbl_50_000_00".tr)), SizedBox(height: 10.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_yet_to_receive".tr, augTwentyThree: "lbl_1_50_000_00".tr)), SizedBox(height: 10.v), Divider()])); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.whiteA700, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.indigo100.withOpacity(0.5), width: 1.h), borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 134.v, width: 343.h, padding: EdgeInsets.all(7.h), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: Container(height: 118.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h)))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 12.h, top: 12.v), child: Text("lbl_type_here".tr, style: CustomTextStyles.bodyLargeGray400)))]))); } 
/// Section Widget
Widget _buildFrame3(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [Column(children: [Container(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.symmetric(horizontal: 4.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder30), child: CustomImageView(imagePath: ImageConstant.imgPlay, height: 60.v, width: 51.h, alignment: Alignment.center)), SizedBox(height: 8.v), Text("lbl_siddhe".tr, textAlign: TextAlign.center, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), Text("lbl_groom".tr.toUpperCase(), textAlign: TextAlign.center, style: theme.textTheme.labelMedium)]), Padding(padding: EdgeInsets.only(left: 31.h), child: Column(children: [Container(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.symmetric(horizontal: 5.h), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.circleBorder30), child: CustomImageView(imagePath: ImageConstant.imgPlayBlueGray700, height: 60.v, width: 48.h, alignment: Alignment.center)), SizedBox(height: 8.v), Text("lbl_shreyasi".tr, textAlign: TextAlign.center, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), Text("lbl_bride".tr.toUpperCase(), textAlign: TextAlign.center, style: theme.textTheme.labelMedium)]))])); } 
/// Common widget
Widget _buildEngagement(BuildContext context, {required String engagement, required String augTwentyThree, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(engagement, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700)), Text(augTwentyThree, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.blueGray900))]); } 
/// Common widget
Widget _buildEVENTCounter(BuildContext context, {required String eVENTCounter, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(eVENTCounter, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.gray700)), CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 16.adaptSize, width: 16.adaptSize)]); } 
/// Common widget
Widget _buildEngagement1(BuildContext context, {required String engagement, required String time, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(engagement, style: CustomTextStyles.titleMedium18.copyWith(color: appTheme.blueGray900)), Padding(padding: EdgeInsets.only(top: 4.v, bottom: 2.v), child: Text(time, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.gray700)))]); } 
/// Common widget
Widget _buildOverview(BuildContext context, {required String overview, required String price, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text(overview, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.gray700)), Spacer(), Container(width: 58.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 2.v), decoration: AppDecoration.fillRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text(price, style: CustomTextStyles.bodySmallRed600.copyWith(color: appTheme.red600))), CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
