import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title_circleimage.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_drop_down.dart';import 'models/khichiq_profile_completion_step_2_charges_two_model.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_2_charges_two_provider.dart';class KhichiqProfileCompletionStep2ChargesTwoScreen extends StatefulWidget {const KhichiqProfileCompletionStep2ChargesTwoScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep2ChargesTwoScreenState createState() =>  KhichiqProfileCompletionStep2ChargesTwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep2ChargesTwoProvider(), child: KhichiqProfileCompletionStep2ChargesTwoScreen()); } 
 }
class KhichiqProfileCompletionStep2ChargesTwoScreenState extends State<KhichiqProfileCompletionStep2ChargesTwoScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildSetYourCharges(context), SizedBox(height: 5.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_be_mindful_always".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 24.v), _buildPhotography(context), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_full_day_charges".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_half_day_charges".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice1(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_per_hour_charges".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice2(context), SizedBox(height: 24.v), Selector<KhichiqProfileCompletionStep2ChargesTwoProvider, KhichiqProfileCompletionStep2ChargesTwoModel?>(selector: (context, provider) => provider.khichiqProfileCompletionStep2ChargesTwoModelObj, builder: (context, khichiqProfileCompletionStep2ChargesTwoModelObj, child) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 30.v, 16.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 14.adaptSize, width: 14.adaptSize)), hintText: "lbl_videography".tr, hintStyle: CustomTextStyles.titleSmallPrimary, items: khichiqProfileCompletionStep2ChargesTwoModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 19.h, top: 30.v, bottom: 30.v), onChanged: (value) {context.read<KhichiqProfileCompletionStep2ChargesTwoProvider>().onSelected(value);});}), SizedBox(height: 25.v), _buildPhotoEditing(context), SizedBox(height: 22.v), Container(height: 8.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700)), SizedBox(height: 12.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgFloatingIcon, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_add_another_service".tr, style: CustomTextStyles.titleSmallPrimary))])))]))))])), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [AppbarTitleCircleimage(imagePath: ImageConstant.imgBaa045e1A455448x48), AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(left: 18.h, top: 14.v, bottom: 10.v))])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildSetYourCharges(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_set_your_charges".tr, style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 3.v), child: Text("lbl_step_2_of_2".tr, style: CustomTextStyles.labelMediumGray700))])); } 
/// Section Widget
Widget _buildPhotography(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 20.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_photography".tr, style: CustomTextStyles.titleSmallPrimary), CustomImageView(imagePath: ImageConstant.imgArrowUpPrimary, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 3.v))])); } 
/// Section Widget
Widget _buildPrice(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2ChargesTwoProvider, TextEditingController?>(selector: (context, provider) => provider.priceController, builder: (context, priceController, child) {return CustomTextFormField(controller: priceController, hintText: "lbl_15_000".tr);})); } 
/// Section Widget
Widget _buildPrice1(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2ChargesTwoProvider, TextEditingController?>(selector: (context, provider) => provider.priceController1, builder: (context, priceController1, child) {return CustomTextFormField(controller: priceController1, hintText: "lbl_8_000".tr);})); } 
/// Section Widget
Widget _buildPrice2(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2ChargesTwoProvider, TextEditingController?>(selector: (context, provider) => provider.priceController2, builder: (context, priceController2, child) {return CustomTextFormField(controller: priceController2, hintText: "lbl_1_500".tr, textInputAction: TextInputAction.done);})); } 
/// Section Widget
Widget _buildPhotoEditing(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 19.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_photo_editing".tr, style: CustomTextStyles.titleSmallPrimary), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 3.v))])); } 
/// Section Widget
Widget _buildSAVEFINISH(BuildContext context) { return CustomElevatedButton(text: "lbl_save_finish".tr, onPressed: () {onTapSAVEFINISH(context);}); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: _buildSAVEFINISH(context)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the khichiqProfileCompletionStep2Complete1eScreen when the action is triggered.
onTapSAVEFINISH(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqProfileCompletionStep2Complete1eScreen, ); } 
 }
