import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_three.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/core/utils/validation_functions.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_1_two_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_1_two_provider.dart';class KhichiqProfileCompletionStep1TwoScreen extends StatefulWidget {const KhichiqProfileCompletionStep1TwoScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep1TwoScreenState createState() =>  KhichiqProfileCompletionStep1TwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep1TwoProvider(), child: KhichiqProfileCompletionStep1TwoScreen()); } 
 }

// ignore_for_file: must_be_immutable
class KhichiqProfileCompletionStep1TwoScreenState extends State<KhichiqProfileCompletionStep1TwoScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: _buildKhichiqProfile(context)))]))), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [Container(padding: EdgeInsets.symmetric(horizontal: 3.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: AppbarImage(imagePath: ImageConstant.imgPlay)), Padding(padding: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 3.v), child: Column(children: [AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(right: 22.h)), AppbarSubtitleThree(text: "msg_upload_profile_picture".tr)]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildKhichiqProfile(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildThirtyThree(context, email: "msg_update_business".tr, vERIFY: "lbl_step_1_of_2".tr), SizedBox(height: 5.v), Text("msg_get_more_exposure".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 22.v), Text("msg_verify_your_email".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), _buildThirtyThree(context, email: "msg_chinmay_kale_sys_com".tr, vERIFY: "lbl_verify".tr), SizedBox(height: 13.v), Text("msg_no_spams_all_i".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 21.v), Text("lbl_website".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<KhichiqProfileCompletionStep1TwoProvider, TextEditingController?>(selector: (context, provider) => provider.thirtyFourController, builder: (context, thirtyFourController, child) {return CustomTextFormField(controller: thirtyFourController, hintText: "msg_enter_instagram".tr, hintStyle: CustomTextStyles.titleMediumGray400);}), SizedBox(height: 24.v), Text("lbl_instagram".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), Selector<KhichiqProfileCompletionStep1TwoProvider, TextEditingController?>(selector: (context, provider) => provider.nameController, builder: (context, nameController, child) {return CustomTextFormField(controller: nameController, hintText: "msg_instagram_com_enter".tr, hintStyle: CustomTextStyles.titleMediumGray400, textInputAction: TextInputAction.done, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});})])); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNEXT(context);})); } 
/// Common widget
Widget _buildThirtyThree(BuildContext context, {required String email, required String vERIFY, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(email, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray900))), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text(vERIFY, style: CustomTextStyles.titleSmallPrimary.copyWith(color: theme.colorScheme.primary)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the khichiqProfileCompletionStep1Otp2bScreen when the action is triggered.
onTapNEXT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqProfileCompletionStep1Otp2bScreen, ); } 
 }
