import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_seven.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/core/utils/validation_functions.dart';import 'widgets/khichiqonboardingdatainputsix_item_widget.dart';import 'models/khichiqonboardingdatainputsix_item_model.dart';import 'models/khichiq_onboarding_data_input_six_model.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_onboarding_data_input_six_provider.dart';class KhichiqOnboardingDataInputSixScreen extends StatefulWidget {const KhichiqOnboardingDataInputSixScreen({Key? key}) : super(key: key);

@override KhichiqOnboardingDataInputSixScreenState createState() =>  KhichiqOnboardingDataInputSixScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqOnboardingDataInputSixProvider(), child: KhichiqOnboardingDataInputSixScreen()); } 
 }

// ignore_for_file: must_be_immutable
class KhichiqOnboardingDataInputSixScreenState extends State<KhichiqOnboardingDataInputSixScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 16.v), child: Column(children: [SizedBox(height: 42.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTellUsAboutYourself(context), SizedBox(height: 20.v), Text("lbl_your_name".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), _buildName(context), SizedBox(height: 22.v), Text("lbl_email".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), _buildEmail(context), SizedBox(height: 23.v), Text("msg_business_freelancing".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), _buildName1(context), SizedBox(height: 22.v), Text("lbl_date_of_birth".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), _buildTwentyTwo(context), SizedBox(height: 22.v), _buildKhichiqOnboardingDataInputSix(context)]))))]))), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgNounStar6104571Primary, margin: EdgeInsets.only(left: 16.h, top: 8.v, bottom: 8.v)), title: AppbarTitle(text: "lbl_khichiq".tr, margin: EdgeInsets.only(left: 10.h)), actions: [AppbarSubtitleSeven(text: "msg_proudly_made_in".tr, margin: EdgeInsets.fromLTRB(12.h, 26.v, 91.h, 17.v))]); } 
/// Section Widget
Widget _buildTellUsAboutYourself(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_tell_us_about_yourself".tr, style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(top: 7.v, bottom: 2.v), child: Text("lbl_step_1_of_2".tr, style: CustomTextStyles.labelMediumGray700))]); } 
/// Section Widget
Widget _buildName(BuildContext context) { return Selector<KhichiqOnboardingDataInputSixProvider, TextEditingController?>(selector: (context, provider) => provider.nameController, builder: (context, nameController, child) {return CustomTextFormField(controller: nameController, hintText: "lbl_chinmay_kale".tr);}); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return Selector<KhichiqOnboardingDataInputSixProvider, TextEditingController?>(selector: (context, provider) => provider.emailController, builder: (context, emailController, child) {return CustomTextFormField(controller: emailController, hintText: "msg_chinmay_kale_sys_com".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}); } 
/// Section Widget
Widget _buildName1(BuildContext context) { return Selector<KhichiqOnboardingDataInputSixProvider, TextEditingController?>(selector: (context, provider) => provider.nameController1, builder: (context, nameController1, child) {return CustomTextFormField(controller: nameController1, hintText: "lbl_sys_weddi".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildTwentyTwo(BuildContext context) { return Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Text("lbl_dd_mm_yyyy".tr, style: CustomTextStyles.titleMediumGray400)), CustomImageView(imagePath: ImageConstant.imgCalender, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(right: 4.h))])); } 
/// Section Widget
Widget _buildKhichiqOnboardingDataInputSix(BuildContext context) { return Consumer<KhichiqOnboardingDataInputSixProvider>(builder: (context, provider, child) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: provider.khichiqOnboardingDataInputSixModelObj.khichiqonboardingdatainputsixItemList.length, itemBuilder: (context, index) {KhichiqonboardingdatainputsixItemModel model = provider.khichiqOnboardingDataInputSixModelObj.khichiqonboardingdatainputsixItemList[index]; return KhichiqonboardingdatainputsixItemWidget(model, changeRadioButton1: (value) {provider.changeRadioButton1(index, value);}, changeRadioButton2: (value) {provider.changeRadioButton2(index, value);}, changeRadioButton3: (value) {provider.changeRadioButton3(index, value);}, changeRadioButton4: (value) {provider.changeRadioButton4(index, value);});});}); } 
/// Section Widget
Widget _buildNEXT(BuildContext context) { return CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNEXT(context);}); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: _buildNEXT(context)); } 
/// Navigates to the khichiqOnboardingDataInputSevenScreen when the action is triggered.
onTapNEXT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqOnboardingDataInputSevenScreen, ); } 
 }
