import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_three.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/core/utils/validation_functions.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_1_email_verified_2c_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_1_email_verified_2c_provider.dart';class KhichiqProfileCompletionStep1EmailVerified2cScreen extends StatefulWidget {const KhichiqProfileCompletionStep1EmailVerified2cScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep1EmailVerified2cScreenState createState() =>  KhichiqProfileCompletionStep1EmailVerified2cScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep1EmailVerified2cProvider(), child: KhichiqProfileCompletionStep1EmailVerified2cScreen()); } 
 }

// ignore_for_file: must_be_immutable
class KhichiqProfileCompletionStep1EmailVerified2cScreenState extends State<KhichiqProfileCompletionStep1EmailVerified2cScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: _buildKhichiqProfile(context)))]))), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [Container(padding: EdgeInsets.symmetric(horizontal: 3.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: AppbarImage(imagePath: ImageConstant.imgPlay)), Padding(padding: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 3.v), child: Column(children: [AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(right: 22.h)), AppbarSubtitleThree(text: "msg_upload_profile_picture".tr)]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildKhichiqProfile(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFortyFour(context, instagramCom: "msg_update_business".tr, sYSWeddings: "lbl_step_1_of_2".tr), SizedBox(height: 5.v), Text("msg_get_more_exposure".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 22.v), Text("msg_verify_your_email".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), Selector<KhichiqProfileCompletionStep1EmailVerified2cProvider, TextEditingController?>(selector: (context, provider) => provider.emailController, builder: (context, emailController, child) {return CustomTextFormField(controller: emailController, hintText: "msg_chinmay_kale_sys_com".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}), SizedBox(height: 10.v), Text("msg_email_verified".tr, style: CustomTextStyles.bodyMediumGreenA700), SizedBox(height: 23.v), Text("lbl_website".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<KhichiqProfileCompletionStep1EmailVerified2cProvider, TextEditingController?>(selector: (context, provider) => provider.fortyTwoController, builder: (context, fortyTwoController, child) {return CustomTextFormField(controller: fortyTwoController, hintText: "msg_enter_instagram".tr, hintStyle: CustomTextStyles.titleMediumGray400, textInputAction: TextInputAction.done);}), SizedBox(height: 24.v), Text("lbl_instagram".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), _buildFortyFour(context, instagramCom: "lbl_instagram_com".tr, sYSWeddings: "lbl_sys_weddings".tr)])); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNEXT(context);})); } 
/// Common widget
Widget _buildFortyFour(BuildContext context, {required String instagramCom, required String sYSWeddings, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(instagramCom, style: CustomTextStyles.titleMediumGray400.copyWith(color: appTheme.gray400))), Padding(padding: EdgeInsets.only(left: 2.h, top: 3.v), child: Text(sYSWeddings, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray900)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the khichiqProfileCompletionStep1Retry2eScreen when the action is triggered.
onTapNEXT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqProfileCompletionStep1Retry2eScreen, ); } 
 }
