import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_three.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_1_otp_error_2d_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_1_otp_error_2d_provider.dart';class KhichiqProfileCompletionStep1OtpError2dScreen extends StatefulWidget {const KhichiqProfileCompletionStep1OtpError2dScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep1OtpError2dScreenState createState() =>  KhichiqProfileCompletionStep1OtpError2dScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep1OtpError2dProvider(), child: KhichiqProfileCompletionStep1OtpError2dScreen()); } 
 }
class KhichiqProfileCompletionStep1OtpError2dScreenState extends State<KhichiqProfileCompletionStep1OtpError2dScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: _buildKhichiqProfile(context)))])), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [Container(padding: EdgeInsets.symmetric(horizontal: 3.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: AppbarImage(imagePath: ImageConstant.imgPlay)), Padding(padding: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 3.v), child: Column(children: [AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(right: 22.h)), AppbarSubtitleThree(text: "msg_upload_profile_picture".tr)]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildKhichiqProfile(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSixtyNine(context, instagramCom: "msg_update_business".tr, sYSWeddings: "lbl_step_1_of_2".tr), SizedBox(height: 5.v), Text("msg_get_more_exposure".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 21.v), Text("lbl_enter_otp".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 48.v, width: 50.h, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 11.v), decoration: AppDecoration.outlineRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.center)), Container(height: 48.v, width: 50.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v), decoration: AppDecoration.outlineRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.centerLeft)), Container(height: 48.v, width: 50.h, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 11.v), decoration: AppDecoration.outlineRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.center)), _buildSignal(context), _buildSignal(context), _buildSignal(context)]), SizedBox(height: 12.v), Text("msg_email_verification".tr, style: CustomTextStyles.bodyMediumRed600), SizedBox(height: 22.v), Text("lbl_website".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<KhichiqProfileCompletionStep1OtpError2dProvider, TextEditingController?>(selector: (context, provider) => provider.sixtyTwoController, builder: (context, sixtyTwoController, child) {return CustomTextFormField(controller: sixtyTwoController, hintText: "msg_enter_instagram".tr, hintStyle: CustomTextStyles.titleMediumGray400, textInputAction: TextInputAction.done);}), SizedBox(height: 24.v), Text("lbl_instagram".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), _buildSixtyNine(context, instagramCom: "lbl_instagram_com".tr, sYSWeddings: "lbl_sys_weddings".tr)])); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: CustomElevatedButton(text: "lbl_next".tr)); } 
/// Common widget
Widget _buildSignal(BuildContext context) { return SizedBox(height: 48.v, width: 50.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 48.v, width: 50.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v), decoration: AppDecoration.outlineRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.centerLeft)))])); } 
/// Common widget
Widget _buildSixtyNine(BuildContext context, {required String instagramCom, required String sYSWeddings, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(instagramCom, style: CustomTextStyles.titleMediumGray400.copyWith(color: appTheme.gray400))), Padding(padding: EdgeInsets.only(left: 2.h, top: 3.v), child: Text(sYSWeddings, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray900)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
