import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_six.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_icon_button.dart';import 'widgets/khichiqleadseditthirteen_item_widget.dart';import 'models/khichiqleadseditthirteen_item_model.dart';import 'models/khichiq_leads_edit_thirteen_model.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_leads_edit_thirteen_provider.dart';class KhichiqLeadsEditThirteenScreen extends StatefulWidget {const KhichiqLeadsEditThirteenScreen({Key? key}) : super(key: key);

@override KhichiqLeadsEditThirteenScreenState createState() =>  KhichiqLeadsEditThirteenScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqLeadsEditThirteenProvider(), child: KhichiqLeadsEditThirteenScreen()); } 
 }
class KhichiqLeadsEditThirteenScreenState extends State<KhichiqLeadsEditThirteenScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_order_details".tr, style: theme.textTheme.titleSmall), SizedBox(height: 7.v), _buildFrameSeventyFour(context), SizedBox(height: 24.v), _buildNextTask(context), SizedBox(height: 6.v), _buildFrameSeventyFive(context), SizedBox(height: 24.v), Text("msg_events_wise_details".tr, style: theme.textTheme.titleSmall), SizedBox(height: 7.v), _buildKhichiqLeadseditThirteen(context), SizedBox(height: 24.v), _buildOrderPayments(context), SizedBox(height: 6.v), _buildFrameSeventyTwo(context), SizedBox(height: 24.v), Text("lbl_notes".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), Selector<KhichiqLeadsEditThirteenProvider, TextEditingController?>(selector: (context, provider) => provider.typehereController, builder: (context, typehereController, child) {return CustomTextFormField(controller: typehereController, hintText: "lbl_type_here".tr, hintStyle: CustomTextStyles.bodyLargeGray400, textInputAction: TextInputAction.done, maxLines: 5, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 23.v), borderDecoration: TextFormFieldStyleHelper.outlineIndigoTL8);}), SizedBox(height: 24.v), Text("lbl_clients".tr, style: theme.textTheme.titleSmall), SizedBox(height: 9.v), _buildFrame(context), SizedBox(height: 13.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgArchive, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_archive_this_order".tr, style: CustomTextStyles.labelLargePrimary))])])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 64.v, leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 24.v, bottom: 24.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgWeddingIcon, margin: EdgeInsets.only(top: 3.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Column(children: [AppbarSubtitleTwo(text: "msg_siddheshwar_shreyasi".tr), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 72.h), child: Row(children: [AppbarSubtitleSix(text: "lbl_wedding3".tr.toUpperCase()), Padding(padding: EdgeInsets.only(bottom: 1.v), child: SizedBox(child: Divider(indent: 9.h))), AppbarSubtitleSix(text: "lbl_upcoming".tr.toUpperCase(), margin: EdgeInsets.only(left: 7.h))]))]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEdit, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v), onTap: () {onTapEDIT(context);})], styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildFrameSeventyFour(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 11.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_pre_wedding4".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_engagement2".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_haldi".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_wedding4".tr, augTwentyThree: "lbl_19_aug_23".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_siddheshwar_9820098200".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 5.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_siddheshwar_anant_yahoo_co_in".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 14.v), Padding(padding: EdgeInsets.symmetric(horizontal: 53.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGmail, height: 20.adaptSize, width: 20.adaptSize), Spacer(flex: 25), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v)), Spacer(flex: 24), CustomImageView(imagePath: ImageConstant.imgSocial, height: 20.adaptSize, width: 20.adaptSize), Spacer(flex: 25), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v)), Spacer(flex: 24), CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), child: CustomImageView(imagePath: ImageConstant.imgCall))]))])); } 
/// Section Widget
Widget _buildNextTask(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_next_task".tr, style: theme.textTheme.titleSmall)), Text("msg_due_by_28_feb_23".tr, style: CustomTextStyles.bodyMediumOrange600)]); } 
/// Section Widget
Widget _buildFrameSeventyFive(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.whiteA700, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.indigo100.withOpacity(0.5), width: 1.h), borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 63.v, width: 343.h, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 6.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: Container(height: 48.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray50, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h)))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 12.h, bottom: 11.v), child: Text("msg_take_confirmation".tr, style: theme.textTheme.titleMedium)))]))); } 
/// Section Widget
Widget _buildKhichiqLeadseditThirteen(BuildContext context) { return Consumer<KhichiqLeadsEditThirteenProvider>(builder: (context, provider, child) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 6.0.v), child: SizedBox(width: 343.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray200)));}, itemCount: provider.khichiqLeadsEditThirteenModelObj.khichiqleadseditthirteenItemList.length, itemBuilder: (context, index) {KhichiqleadseditthirteenItemModel model = provider.khichiqLeadsEditThirteenModelObj.khichiqleadseditthirteenItemList[index]; return KhichiqleadseditthirteenItemWidget(model, onTapEVENTCounter: () {onTapEVENTCounter(context);});});}); } 
/// Section Widget
Widget _buildOrderPayments(BuildContext context) { return Row(children: [Text("lbl_order_payments".tr, style: theme.textTheme.titleSmall), Spacer(), CustomImageView(imagePath: ImageConstant.imgFloatingIcon, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 6.h, bottom: 2.v), child: Text("lbl_add".tr, style: CustomTextStyles.labelLargePrimary))]); } 
/// Section Widget
Widget _buildFrameSeventyTwo(BuildContext context) { return Container(decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 8.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_overview".tr, style: theme.textTheme.bodySmall), Spacer(), Container(width: 58.h, padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 1.v), decoration: AppDecoration.fillRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_payment".tr.toUpperCase(), style: CustomTextStyles.bodySmallRed600)), CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h))])), SizedBox(height: 9.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_quoted".tr, augTwentyThree: "lbl_2_50_000_00".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_received".tr, augTwentyThree: "lbl_50_000_00".tr)), SizedBox(height: 8.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 12.h), child: _buildEngagement(context, engagement: "lbl_yet_to_receive".tr, augTwentyThree: "lbl_1_50_000_00".tr)), SizedBox(height: 8.v), Divider()])); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(children: [Container(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.symmetric(horizontal: 4.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder30), child: CustomImageView(imagePath: ImageConstant.imgPlay, height: 60.v, width: 51.h, alignment: Alignment.center)), SizedBox(height: 8.v), Text("lbl_siddhe".tr, style: theme.textTheme.titleSmall), SizedBox(height: 3.v), Text("lbl_groom".tr.toUpperCase(), style: theme.textTheme.labelMedium)])), Padding(padding: EdgeInsets.only(left: 31.h, top: 1.v), child: Column(children: [Container(height: 60.adaptSize, width: 60.adaptSize, padding: EdgeInsets.symmetric(horizontal: 5.h), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.circleBorder30), child: CustomImageView(imagePath: ImageConstant.imgPlayBlueGray700, height: 60.v, width: 48.h, alignment: Alignment.center)), SizedBox(height: 9.v), Text("lbl_shreyasi".tr, style: theme.textTheme.titleSmall), SizedBox(height: 2.v), Text("lbl_bride".tr.toUpperCase(), style: theme.textTheme.labelMedium)]))])); } 
/// Common widget
Widget _buildEngagement(BuildContext context, {required String engagement, required String augTwentyThree, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(engagement, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700)), Text(augTwentyThree, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.blueGray900))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the khichiqLeadsCreateNewFortytwoScreen when the action is triggered.
onTapEDIT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqLeadsCreateNewFortytwoScreen, ); } 
/// Navigates to the khichiqLeadsEditFourteenScreen when the action is triggered.
onTapEVENTCounter(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqLeadsEditFourteenScreen, ); } 
 }
