import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_seven.dart';import 'widgets/candidphotographer_item_widget.dart';import 'models/candidphotographer_item_model.dart';import 'models/khichiq_onboarding_data_input_7a_model.dart';import 'package:vtracku_s_application6/widgets/custom_checkbox_button.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_onboarding_data_input_7a_provider.dart';class KhichiqOnboardingDataInput7aScreen extends StatefulWidget {const KhichiqOnboardingDataInput7aScreen({Key? key}) : super(key: key);

@override KhichiqOnboardingDataInput7aScreenState createState() =>  KhichiqOnboardingDataInput7aScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqOnboardingDataInput7aProvider(), child: KhichiqOnboardingDataInput7aScreen()); } 
 }
class KhichiqOnboardingDataInput7aScreenState extends State<KhichiqOnboardingDataInput7aScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 16.v), child: Column(children: [SizedBox(height: 42.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSelectYourPrimary(context), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_you_can_select_all".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 34.v), _buildCandidPhotographer(context), SizedBox(height: 11.v), Container(height: 28.v, width: 237.h, margin: EdgeInsets.only(left: 16.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgSmartphone, height: 28.adaptSize, width: 28.adaptSize, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 34.h)), _buildSocialMediaManager(context)])), SizedBox(height: 12.v), Divider(), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCheckboxActive, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.symmetric(vertical: 5.v)), CustomImageView(imagePath: ImageConstant.imgManager, height: 28.adaptSize, width: 28.adaptSize, margin: EdgeInsets.only(left: 16.h)), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v, bottom: 1.v), child: Text("msg_business_manager".tr, style: theme.textTheme.bodyLarge))])), SizedBox(height: 12.v), Divider(), SizedBox(height: 11.v), Align(alignment: Alignment.centerRight, child: GestureDetector(onTap: () {onTapHide(context);}, child: Padding(padding: EdgeInsets.only(right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("lbl_hide".tr, style: CustomTextStyles.titleSmallPrimary), CustomImageView(imagePath: ImageConstant.imgArrowUp, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h))]))))]))))])), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgNounStar6104571Primary), AppbarTitle(text: "lbl_khichiq".tr, margin: EdgeInsets.only(left: 10.h, top: 7.v, bottom: 5.v))])), actions: [AppbarSubtitleSeven(text: "msg_proudly_made_in".tr, margin: EdgeInsets.fromLTRB(12.h, 26.v, 59.h, 17.v))]); } 
/// Section Widget
Widget _buildSelectYourPrimary(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_select_your_primary".tr, style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(left: 26.h, top: 7.v, bottom: 2.v), child: Text("lbl_step_2_of_2".tr, style: CustomTextStyles.labelMediumGray700))]))); } 
/// Section Widget
Widget _buildCandidPhotographer(BuildContext context) { return Consumer<KhichiqOnboardingDataInput7aProvider>(builder: (context, provider, child) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 5.5.v), child: SizedBox(width: double.maxFinite, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray200)));}, itemCount: provider.khichiqOnboardingDataInput7aModelObj.candidphotographerItemList.length, itemBuilder: (context, index) {CandidphotographerItemModel model = provider.khichiqOnboardingDataInput7aModelObj.candidphotographerItemList[index]; return CandidphotographerItemWidget(model);});}); } 
/// Section Widget
Widget _buildSocialMediaManager(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 1.v), child: Selector<KhichiqOnboardingDataInput7aProvider, bool?>(selector: (context, provider) => provider.socialMediaManager, builder: (context, socialMediaManager, child) {return CustomCheckboxButton(alignment: Alignment.bottomCenter, text: "msg_social_media_manager".tr, value: socialMediaManager, textStyle: theme.textTheme.bodyLarge, onChange: (value) {context.read<KhichiqOnboardingDataInput7aProvider>().changeCheckBox1(value);});}))); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: CustomElevatedButton(text: "lbl_select".tr, onPressed: () {onTapSELECT(context);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the khichiqOnboardingDataInputSevenScreen when the action is triggered.
onTapHide(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqOnboardingDataInputSevenScreen, ); } 
/// Navigates to the khichiqOnboardingDataInputEightScreen when the action is triggered.
onTapSELECT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqOnboardingDataInputEightScreen, ); } 
 }
