import 'package:vtracku_s_application6/widgets/custom_icon_button.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_1_dp_crop_2m_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_1_dp_crop_2m_provider.dart';class KhichiqProfileCompletionStep1DpCrop2mDialog extends StatefulWidget {const KhichiqProfileCompletionStep1DpCrop2mDialog({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep1DpCrop2mDialogState createState() =>  KhichiqProfileCompletionStep1DpCrop2mDialogState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep1DpCrop2mProvider(), child: KhichiqProfileCompletionStep1DpCrop2mDialog()); } 
 }
class KhichiqProfileCompletionStep1DpCrop2mDialogState extends State<KhichiqProfileCompletionStep1DpCrop2mDialog> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(margin: EdgeInsets.only(left: 32.h, right: 32.h, bottom: 161.v), padding: EdgeInsets.fromLTRB(10.h, 9.v, 10.h, 10.v), decoration: AppDecoration.outlineGray300011, child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBaa045e1A4554308x231, height: 308.v, width: 231.h, margin: EdgeInsets.only(top: 10.v)), Padding(padding: EdgeInsets.only(left: 12.h, bottom: 300.v), child: CustomIconButton(height: 18.adaptSize, width: 18.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgClose)))]))), SizedBox(height: 18.v), Text("lbl_crop_save".tr, style: CustomTextStyles.titleMedium18), SizedBox(height: 6.v), Container(width: 225.h, margin: EdgeInsets.symmetric(horizontal: 32.h), child: Text("msg_make_sure_your_face".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.29))), SizedBox(height: 21.v), CustomElevatedButton(text: "lbl_save".tr, onPressed: () {onTapSAVE(context);})]))); } 
/// Navigates to the khichiqProfileCompletionStep1Dp2kOneScreen when the action is triggered.
onTapSAVE(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqProfileCompletionStep1Dp2kOneScreen, ); } 
 }
