import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:vtracku_s_application6/widgets/custom_phone_number.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_onboarding_1a_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_onboarding_1a_provider.dart';class KhichiqOnboarding1aScreen extends StatefulWidget {const KhichiqOnboarding1aScreen({Key? key}) : super(key: key);

@override KhichiqOnboarding1aScreenState createState() =>  KhichiqOnboarding1aScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqOnboarding1aProvider(), child: KhichiqOnboarding1aScreen()); } 
 }
class KhichiqOnboarding1aScreenState extends State<KhichiqOnboarding1aScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 60.v), Expanded(child: SingleChildScrollView(child: SizedBox(height: 756.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgWeddingPhotogr, height: 299.v, width: 290.h, alignment: Alignment.topCenter), _buildLoremIpsumDolor(context), Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.outlineGray, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_mobile_number".tr, style: CustomTextStyles.labelLargeBluegray900)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Consumer<KhichiqOnboarding1aProvider>(builder: (context, provider, child) {return CustomPhoneNumber(country: provider.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: provider.phoneNumberController, onTap: (Country value) {context.read<KhichiqOnboarding1aProvider>().changeCountry(value);});})), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_it_s_new_it_s".tr, style: CustomTextStyles.bodyMediumGray500)), SizedBox(height: 31.v), _buildSUBMIT(context)])))]))))])))); } 
/// Section Widget
Widget _buildLoremIpsumDolor(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 31.h, right: 31.h, bottom: 300.v), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 312.h, child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray500.copyWith(height: 1.29))), SizedBox(height: 21.v), SizedBox(height: 6.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: appTheme.blueGray900, dotColor: appTheme.blueGray100, dotHeight: 6.v, dotWidth: 6.h)))]))); } 
/// Section Widget
Widget _buildSUBMIT(BuildContext context) { return SizedBox(height: 312.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImg2dafcb42cfa01, height: 268.v, width: 375.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgImg2dafcb42cfa0148x375, height: 48.v, width: 375.h, alignment: Alignment.bottomCenter), CustomElevatedButton(width: 343.h, text: "lbl_submit".tr, margin: EdgeInsets.only(bottom: 34.v), onPressed: () {onTapSUBMIT(context);}, alignment: Alignment.bottomCenter)])); } 
/// Navigates to the khichiqOnboardingOtpInputFiveScreen when the action is triggered.
onTapSUBMIT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqOnboardingOtpInputFiveScreen, ); } 
 }
