import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_three.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_1_retry_2e_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_1_retry_2e_provider.dart';import 'package:vtracku_s_application6/presentation/khichiq_profile_completion_step_1_dp_popup_2l_bottomsheet/khichiq_profile_completion_step_1_dp_popup_2l_bottomsheet.dart';class KhichiqProfileCompletionStep1Retry2eScreen extends StatefulWidget {const KhichiqProfileCompletionStep1Retry2eScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep1Retry2eScreenState createState() =>  KhichiqProfileCompletionStep1Retry2eScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep1Retry2eProvider(), child: KhichiqProfileCompletionStep1Retry2eScreen()); } 
 }
class KhichiqProfileCompletionStep1Retry2eScreenState extends State<KhichiqProfileCompletionStep1Retry2eScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: _buildKhichiqProfile(context)))])), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Row(children: [Container(padding: EdgeInsets.symmetric(horizontal: 3.h), decoration: AppDecoration.fillAmberA.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: AppbarImage(imagePath: ImageConstant.imgPlay)), Padding(padding: EdgeInsets.only(left: 18.h, top: 6.v, bottom: 3.v), child: Column(children: [AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(right: 22.h)), AppbarSubtitleThree(text: "msg_upload_profile_picture".tr)]))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildKhichiqProfile(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTwentyFive(context, email: "msg_update_business".tr, vERIFY: "lbl_step_1_of_2".tr), SizedBox(height: 5.v), Text("msg_get_more_exposure".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 22.v), Text("msg_verify_your_email".tr, style: theme.textTheme.labelLarge), SizedBox(height: 6.v), _buildTwentyFive(context, email: "msg_chinmay_kale_sys_com".tr, vERIFY: "lbl_verify".tr), SizedBox(height: 22.v), Text("lbl_website".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), Selector<KhichiqProfileCompletionStep1Retry2eProvider, TextEditingController?>(selector: (context, provider) => provider.twentySixController, builder: (context, twentySixController, child) {return CustomTextFormField(controller: twentySixController, hintText: "msg_enter_instagram".tr, hintStyle: CustomTextStyles.titleMediumGray400, textInputAction: TextInputAction.done);}), SizedBox(height: 54.v), Text("lbl_instagram".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), _buildTwentyFive(context, email: "lbl_instagram_com".tr, vERIFY: "lbl_sys_weddings".tr)])); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNEXT(context);})); } 
/// Common widget
Widget _buildTwentyFive(BuildContext context, {required String email, required String vERIFY, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(email, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray900))), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text(vERIFY, style: CustomTextStyles.titleSmallPrimary.copyWith(color: theme.colorScheme.primary)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 

/// Displays a bottom sheet widget using the [showModalBottomSheet] method 
/// of the [Scaffold] class with [isScrollControlled] set to true.
///
/// The bottom sheet is built using the [KhichiqProfileCompletionStep1DpPopup2lBottomsheet]
/// class and the [builder] method of the bottom sheet is passed the
/// [BuildContext] object.
onTapNEXT(BuildContext context) { showModalBottomSheet(context: NavigatorService.navigatorKey.currentContext!, builder: (_)=>KhichiqProfileCompletionStep1DpPopup2lBottomsheet.builder(NavigatorService.navigatorKey.currentContext!),isScrollControlled: true); } 
 }
