import 'package:vtracku_s_application6/widgets/custom_rating_bar.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_2_complete_1e_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_2_complete_1e_provider.dart';class KhichiqProfileCompletionStep2Complete1eScreen extends StatefulWidget {const KhichiqProfileCompletionStep2Complete1eScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep2Complete1eScreenState createState() =>  KhichiqProfileCompletionStep2Complete1eScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep2Complete1eProvider(), child: KhichiqProfileCompletionStep2Complete1eScreen()); } 
 }
class KhichiqProfileCompletionStep2Complete1eScreenState extends State<KhichiqProfileCompletionStep2Complete1eScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildBAAEA(context), SizedBox(height: 24.v), CustomRatingBar(initialRating: 0), SizedBox(height: 14.v), Text("msg_profile_completed".tr, style: CustomTextStyles.titleMediumWhiteA70018), SizedBox(height: 61.v), Text("lbl_chinmay".tr, style: CustomTextStyles.headlineLargeYellowA700), SizedBox(height: 2.v), Text("msg_you_are_a_pro_khichiq".tr, style: CustomTextStyles.titleMediumWhiteA70018)])))), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
Widget _buildBAAEA(BuildContext context) { return SizedBox(height: 305.v, width: 373.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgClipPathGroup, height: 154.v, width: 373.h, alignment: Alignment.topCenter), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 88.h, right: 85.h), padding: EdgeInsets.all(20.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.circleBorder100), child: Container(height: 160.adaptSize, width: 160.adaptSize, padding: EdgeInsets.all(25.h), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.circleBorder80), child: CustomImageView(imagePath: ImageConstant.imgBaa045e1A4554110x110, height: 110.adaptSize, width: 110.adaptSize, radius: BorderRadius.circular(54.h), alignment: Alignment.center))))])); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineBlack, child: CustomElevatedButton(text: "lbl_take_me_to_dash".tr, buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.titleSmallPrimarySemiBold, onPressed: () {onTapTAKEMETODASH(context);})); } 
/// Navigates to the khichiqHomeSevenScreen when the action is triggered.
onTapTAKEMETODASH(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqHomeSevenScreen, ); } 
 }
