import 'package:carousel_slider/carousel_slider.dart';import 'widgets/trackyourpayments_item_widget.dart';import 'models/trackyourpayments_item_model.dart';import 'models/khichiq_onboarding_otp_input_five_model.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_onboarding_otp_input_five_provider.dart';class KhichiqOnboardingOtpInputFiveScreen extends StatefulWidget {const KhichiqOnboardingOtpInputFiveScreen({Key? key}) : super(key: key);

@override KhichiqOnboardingOtpInputFiveScreenState createState() =>  KhichiqOnboardingOtpInputFiveScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqOnboardingOtpInputFiveProvider(), child: KhichiqOnboardingOtpInputFiveScreen()); } 
 }
class KhichiqOnboardingOtpInputFiveScreenState extends State<KhichiqOnboardingOtpInputFiveScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 60.v), Expanded(child: SingleChildScrollView(child: SizedBox(height: 756.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgWeddingPhotogr, height: 299.v, width: 290.h, alignment: Alignment.topCenter), _buildTrackYourPayments(context), Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.outlineGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Selector<KhichiqOnboardingOtpInputFiveProvider, TextEditingController?>(selector: (context, provider) => provider.enterOTPController, builder: (context, enterOTPController, child) {return CustomTextFormField(width: 225.h, controller: enterOTPController, hintText: "lbl_enter_otp".tr, hintStyle: CustomTextStyles.labelLargeBluegray900, textInputAction: TextInputAction.done, alignment: Alignment.centerLeft);})), SizedBox(height: 7.v), _buildSignal(context), SizedBox(height: 12.v), _buildWeVeSentAnOTP(context), SizedBox(height: 32.v), _buildVERIFY(context)])))]))))])))); } 
/// Section Widget
Widget _buildTrackYourPayments(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 31.h, right: 31.h, bottom: 300.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Consumer<KhichiqOnboardingOtpInputFiveProvider>(builder: (context, provider, child) {return CarouselSlider.builder(options: CarouselOptions(height: 87.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {provider.sliderIndex = index;}), itemCount: provider.khichiqOnboardingOtpInputFiveModelObj.trackyourpaymentsItemList.length, itemBuilder: (context, index, realIndex) {TrackyourpaymentsItemModel model = provider.khichiqOnboardingOtpInputFiveModelObj.trackyourpaymentsItemList[index]; return TrackyourpaymentsItemWidget(model);});}), SizedBox(height: 21.v), Consumer<KhichiqOnboardingOtpInputFiveProvider>(builder: (context, provider, child) {return SizedBox(height: 6.v, child: AnimatedSmoothIndicator(activeIndex: provider.sliderIndex, count: provider.khichiqOnboardingOtpInputFiveModelObj.trackyourpaymentsItemList.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: appTheme.blueGray900, dotColor: appTheme.blueGray100, dotHeight: 6.v, dotWidth: 6.h)));})]))); } 
/// Section Widget
Widget _buildSignal(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 48.v, width: 50.h, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 11.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.center)), Container(height: 48.v, width: 50.h, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignal, height: 24.v, width: 22.h, alignment: Alignment.centerLeft)), Container(height: 48.v, width: 50.h, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 11.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgSignalPrimary, height: 24.v, width: 22.h, alignment: Alignment.center)), Container(height: 48.v, width: 50.h, margin: EdgeInsets.only(left: 8.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h))), Container(height: 48.v, width: 50.h, margin: EdgeInsets.only(left: 8.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h))), Container(height: 48.v, width: 50.h, margin: EdgeInsets.only(left: 8.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: appTheme.indigo100, width: 1.h)))])); } 
/// Section Widget
Widget _buildWeVeSentAnOTP(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_we_ve_sent_an_otp".tr, style: CustomTextStyles.bodyMediumGray500), RichText(text: TextSpan(children: [TextSpan(text: "lbl_resend".tr, style: CustomTextStyles.bodyMediumff999999), TextSpan(text: "lbl_00_30".tr, style: CustomTextStyles.bodyMediumff4a8af8)]), textAlign: TextAlign.left)])); } 
/// Section Widget
Widget _buildVERIFY(BuildContext context) { return SizedBox(height: 311.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImg2dafcb42cfa01, height: 268.v, width: 375.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgImg2dafcb42cfa0148x375, height: 48.v, width: 375.h, alignment: Alignment.bottomCenter), CustomElevatedButton(width: 343.h, text: "lbl_verify".tr, margin: EdgeInsets.only(bottom: 34.v), onPressed: () {onTapVERIFY(context);}, alignment: Alignment.bottomCenter)])); } 
/// Navigates to the khichiqOnboardingDataInputSixScreen when the action is triggered.
onTapVERIFY(BuildContext context) { NavigatorService.pushNamed(AppRoutes.khichiqOnboardingDataInputSixScreen, ); } 
 }
