import 'package:vtracku_s_application6/widgets/app_bar/custom_app_bar.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_leading_image.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_title_circleimage.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_subtitle_two.dart';import 'package:vtracku_s_application6/widgets/app_bar/appbar_trailing_image.dart';import 'package:vtracku_s_application6/widgets/custom_text_form_field.dart';import 'package:vtracku_s_application6/widgets/custom_elevated_button.dart';import 'models/khichiq_profile_completion_step_2_manager_1d_model.dart';import 'package:flutter/material.dart';import 'package:vtracku_s_application6/core/app_export.dart';import 'provider/khichiq_profile_completion_step_2_manager_1d_provider.dart';class KhichiqProfileCompletionStep2Manager1dScreen extends StatefulWidget {const KhichiqProfileCompletionStep2Manager1dScreen({Key? key}) : super(key: key);

@override KhichiqProfileCompletionStep2Manager1dScreenState createState() =>  KhichiqProfileCompletionStep2Manager1dScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KhichiqProfileCompletionStep2Manager1dProvider(), child: KhichiqProfileCompletionStep2Manager1dScreen()); } 
 }
class KhichiqProfileCompletionStep2Manager1dScreenState extends State<KhichiqProfileCompletionStep2Manager1dScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 10.v), child: Column(children: [SizedBox(height: 48.v), Expanded(child: SingleChildScrollView(child: _buildKhichiqProfile(context)))])), bottomNavigationBar: _buildBOTTOMNAV(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [AppbarTitleCircleimage(imagePath: ImageConstant.imgBaa045e1A455448x48), AppbarSubtitleTwo(text: "lbl_hi_chinmay".tr, margin: EdgeInsets.only(left: 18.h, top: 14.v, bottom: 10.v))])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgCancel, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))]); } 
/// Section Widget
Widget _buildPrice(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2Manager1dProvider, TextEditingController?>(selector: (context, provider) => provider.priceController, builder: (context, priceController, child) {return CustomTextFormField(controller: priceController, hintText: "lbl_15_000".tr);})); } 
/// Section Widget
Widget _buildPrice1(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2Manager1dProvider, TextEditingController?>(selector: (context, provider) => provider.priceController1, builder: (context, priceController1, child) {return CustomTextFormField(controller: priceController1, hintText: "lbl_8_000".tr);})); } 
/// Section Widget
Widget _buildPrice2(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Selector<KhichiqProfileCompletionStep2Manager1dProvider, TextEditingController?>(selector: (context, provider) => provider.priceController2, builder: (context, priceController2, child) {return CustomTextFormField(controller: priceController2, hintText: "lbl_1_500".tr, textInputAction: TextInputAction.done);})); } 
/// Section Widget
Widget _buildKhichiqProfile(BuildContext context) { return Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_set_your_charges".tr, style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 3.v), child: Text("lbl_step_2_of_2".tr, style: CustomTextStyles.labelMediumGray700))])), SizedBox(height: 5.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_be_mindful_always".tr, style: theme.textTheme.bodyMedium))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 20.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_business_manager".tr, style: CustomTextStyles.titleSmallPrimary), CustomImageView(imagePath: ImageConstant.imgArrowUpPrimary, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 3.v))])), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_monthly_salary".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_full_day_charges2".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice1(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_per_hour_charges".tr, style: theme.textTheme.labelLarge))), SizedBox(height: 6.v), _buildPrice2(context), SizedBox(height: 12.v), Container(height: 8.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700))])); } 
/// Section Widget
Widget _buildSAVEFINISH(BuildContext context) { return CustomElevatedButton(text: "lbl_save_finish".tr); } 
/// Section Widget
Widget _buildBOTTOMNAV(BuildContext context) { return Container(margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 34.v), decoration: AppDecoration.outlineGray30001, child: _buildSAVEFINISH(context)); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
